version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python -m unittest it_shanbay.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test

